import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';

const url = process.env.VIEWER_URL || 'http://127.0.0.1:4330/';
const output = path.resolve('verification');
await fs.mkdir(output, { recursive: true });

const browser = await chromium.launch({ headless: true });
try {
  for (const viewport of [{ width: 390, height: 844, name: 'mobile' }, { width: 1280, height: 800, name: 'desktop' }]) {
    const page = await browser.newPage({ viewport });
    const errors = [];
    page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
    page.on('pageerror', (error) => errors.push(error.message));
    await page.goto(url, { waitUntil: 'domcontentloaded' });
    await page.waitForSelector('.brand-mark');
    await page.waitForSelector('#loading', { state: 'hidden', timeout: 120_000 });
    await page.locator('#acupuncture-menu summary').click();
    if (await page.locator('#acupuncture-zones').getAttribute('aria-pressed') !== 'true') throw new Error(`${viewport.name}: skin zones are not enabled by default`);
    await page.locator('#acupuncture-zones').click();
    if ((await page.locator('#acupuncture-count').textContent()).includes('皮')) throw new Error(`${viewport.name}: skin-zone indicator did not turn off`);
    await page.locator('#acupuncture-zones').click();
    await page.locator('#acupuncture-menu summary').click();
    await page.locator('#layers-menu summary').click();
    await page.locator('#section-left').click();
    await page.waitForFunction(() => document.querySelector('#section-count')?.textContent === 'Hide L');
    if (await page.locator('#section-left').getAttribute('aria-pressed') !== 'true') throw new Error(`${viewport.name}: Hide L section state was not applied`);
    await page.screenshot({ path: path.join(output, `acu-map-${viewport.name}-section.png`), fullPage: true });
    await page.locator('#line-style').click();
    if (await page.locator('#line-style').getAttribute('aria-pressed') !== 'false') throw new Error(`${viewport.name}: line style toggle did not switch to solid`);
    await page.locator('#line-style').click();
    await page.locator('#section-full').click();
    await page.locator('#layers-menu summary').click();
    await page.locator('#ruler-menu summary').click();
    if (await page.locator('#ruler-master').getAttribute('aria-pressed') !== 'true') throw new Error(`${viewport.name}: automatic rulers should be on by default`);
    if (await page.locator('#ruler-count').textContent() !== 'Select point') throw new Error(`${viewport.name}: rulers should wait for point selection`);
    await page.locator('#ruler-menu summary').click();
    await page.locator('#point-panel-toggle').click();
    await page.waitForSelector('#point-panel.is-open');
    if (await page.locator('#point-meridians button').count() !== 14) throw new Error(`${viewport.name}: Find Point does not list 14 meridians`);
    await page.locator('#point-meridians button[data-channel="LI"]').click();
    await page.waitForFunction(() => document.querySelector('#point-panel-title')?.textContent === 'Large intestine meridian');
    const firstTile = page.locator('#structures .point-tile').first();
    const tileBox = await firstTile.boundingBox();
    if (!tileBox || Math.abs(tileBox.width - tileBox.height) > 2) throw new Error(`${viewport.name}: point tiles are not square`);
    await page.locator('#search').fill('LI4');
    await page.waitForFunction(() => document.querySelectorAll('#structures .point-tile').length === 1);
    const result = page.locator('#structures .point-tile').first();
    const box = await result.boundingBox();
    if (!box || box.height < 44) throw new Error(`${viewport.name}: search result touch target is too small`);
    await page.screenshot({ path: path.join(output, `acu-map-${viewport.name}.png`), fullPage: true });
    await result.click();
    await page.waitForSelector('#point-panel', { state: 'attached' });
    if (await page.locator('#point-panel').getAttribute('aria-hidden') !== 'true') throw new Error(`${viewport.name}: Find Point panel did not slide closed after selection`);
    await page.waitForFunction(() => document.querySelector('#point-summary-label')?.textContent === 'Large Intestine 4 · Hégǔ · 合谷');
    if (!(await page.locator('#selection-toggle').getAttribute('aria-label'))?.includes('Both sides selected')) throw new Error(`${viewport.name}: menu selection did not select both sides`);
    if (await page.locator('#selection-drawer').getAttribute('aria-hidden') !== 'true') throw new Error(`${viewport.name}: full details opened without an explicit action`);
    await page.locator('#selection-toggle').click();
    await page.waitForSelector('#selection-drawer.is-open');
    await page.waitForFunction(() => document.querySelector('#selected-name')?.textContent === 'Large Intestine 4 · Hégǔ · 合谷');
    await page.waitForFunction(() => document.querySelector('#ruler-count')?.textContent === 'LI4 · 3', undefined, { timeout: 120_000 });
    await page.locator('#ruler-menu summary').click();
    if (!(await page.locator('#ruler-selection').textContent()).includes('LI4 uses 3 reference marks')) throw new Error(`${viewport.name}: selected point ruler summary is wrong`);
    await page.screenshot({ path: path.join(output, `acu-map-${viewport.name}-rulers.png`), fullPage: true });
    await page.locator('#ruler-menu summary').click();
    await page.screenshot({ path: path.join(output, `acu-map-${viewport.name}-point.png`), fullPage: true });
    await page.locator('#close-selection').click();
    await page.locator('#prescription-toggle').click();
    await page.waitForSelector('#prescription-drawer.is-open');
    await page.locator('#prescription-search').fill('Common Cold');
    const libraryCard = page.locator('#library-prescriptions .prescription-card').first();
    await libraryCard.locator('.prescription-select').click();
    if (await libraryCard.getAttribute('aria-pressed') !== 'true') throw new Error(`${viewport.name}: built-in prescription did not activate`);
    if (await page.locator('#clear-prescription').isDisabled()) throw new Error(`${viewport.name}: active prescription cannot be cleared`);
    await page.locator('#new-prescription').click();
    await page.locator('#prescription-name').fill('UI test combination');
    await page.locator('#prescription-description').fill('Saved with a custom description.');
    await page.locator('#prescription-points').fill('LI4, LU7, GB20');
    await page.locator('#preview-prescription').click();
    if (!(await page.locator('#prescription-editor-status').textContent()).includes('Previewing 3 points')) throw new Error(`${viewport.name}: custom point preview failed`);
    await page.locator('#save-prescription').click();
    await page.waitForFunction(() => document.querySelector('#saved-prescriptions')?.textContent?.includes('UI test combination'));
    const saved = JSON.parse(await page.evaluate(() => localStorage.getItem('acu-map-prescriptions-v1') || '[]'));
    if (saved[0]?.description !== 'Saved with a custom description.' || saved[0]?.points?.length !== 3) throw new Error(`${viewport.name}: custom prescription was not persisted correctly`);
    await page.screenshot({ path: path.join(output, `acu-map-${viewport.name}-prescriptions.png`), fullPage: true });
    if (errors.length) throw new Error(`${viewport.name}: browser errors: ${errors.join(' | ')}`);
    await page.close();
  }
  console.log('Acu Map UI checks passed at 390x844 and 1280x800.');
} finally {
  await browser.close();
}
