import * as THREE from 'three';
import {pinyin} from 'pinyin-pro';

export const ACUPUNCTURE_CHANNELS=[
 ['LU','Lung','#c9d5d8'],['LI','Large intestine','#f1f3ee'],['ST','Stomach','#f2dc4a'],['SP','Spleen','#e98632'],
 ['HT','Heart','#a96bd2'],['SI','Small intestine','#8a72d4'],['BL','Bladder','#4b72e8'],['KI','Kidney','#4055bd'],
 ['PC','Pericardium','#d45359'],['TE','Triple energizer','#ef655e'],['GB','Gallbladder','#75cb58'],['LR','Liver','#3d9f62'],
 ['CV','Conception vessel','#54c5b0'],['GV','Governing vessel','#e78bb2'],
];

const CHANNELS=new Map(ACUPUNCTURE_CHANNELS.map(([id,name,color])=>[id,{id,name,color:new THREE.Color(color)}]));
const SURFACE_OFFSET=.055;

function createPointTexture(){const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const context=canvas.getContext('2d'),gradient=context.createRadialGradient(32,32,4,32,32,30);gradient.addColorStop(0,'rgba(255,255,255,1)');gradient.addColorStop(.72,'rgba(255,255,255,1)');gradient.addColorStop(.86,'rgba(255,255,255,.92)');gradient.addColorStop(1,'rgba(255,255,255,0)');context.fillStyle=gradient;context.fillRect(0,0,64,64);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;}

function createLabelTexture(chinese){const canvas=document.createElement('canvas'),context=canvas.getContext('2d');context.font='700 42px "Microsoft YaHei", "PingFang SC", system-ui, sans-serif';const textWidth=Math.ceil(context.measureText(chinese).width);canvas.width=Math.max(96,textWidth+28);canvas.height=64;context.font='700 42px "Microsoft YaHei", "PingFang SC", system-ui, sans-serif';context.textAlign='center';context.textBaseline='middle';context.lineJoin='round';context.strokeStyle='rgba(6,13,17,.96)';context.lineWidth=7;context.strokeText(chinese,canvas.width/2,33);context.fillStyle='#f8f3e7';context.fillText(chinese,canvas.width/2,33);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;return {texture,aspect:canvas.width/canvas.height};}

function nativePosition(point){const [x,y,z]=point.sourcePosition;return new THREE.Vector3(-x,y,z);}
function cloneModels(models={}){const output={Male:{},Female:{}};for(const model of Object.keys(output))for(const [key,value] of Object.entries(models[model]||{}))if(Array.isArray(value)&&value.length===3&&value.every(Number.isFinite))output[model][key]=value.slice();return output;}
function titleCase(value=''){return value.replace(/\b\w/g,character=>character.toUpperCase());}
function pointLabel(point,channel){const chinese=point.names?.chinese,sourcePinyin=point.names?.pinyin||point.displayName||point.id,romanized=chinese?pinyin(chinese,{toneType:'symbol',type:'array'}).join(''):sourcePinyin,pinyinName=romanized.charAt(0).toLocaleUpperCase()+romanized.slice(1);return `${titleCase(channel.name)} ${point.number} · ${pinyinName}${chinese?` · ${chinese}`:''}`;}

export class AcupunctureLayer{
 constructor(scene,onSelect,onEditState=()=>{}){this.scene=scene;this.onSelect=onSelect;this.onEditState=onEditState;this.zoneGroup=new THREE.Group();this.zoneGroup.name='Computed meridian skin zones';this.group=new THREE.Group();this.group.name='Native APK acupuncture overlay';this.scene.add(this.zoneGroup,this.group);this.zoneRoot=null;this.pointTexture=createPointTexture();this.data=null;this.surfacePaths=null;this.model='Male';this.showPoints=false;this.showLines=false;this.showZones=false;this.labelChannel=null;this.dashed=true;this.channels=new Set(CHANNELS.keys());this.pointObject=null;this.highlightObject=null;this.highlightIds=new Set();this.pointRecords=[];this.recordByKey=new Map();this.selected=null;this.selectedKeys=new Set();this.editing=false;this.dragging=null;this.overrides={Male:{},Female:{}};this.history=[];this.dirty=false;this.reduceMotion=matchMedia?.('(prefers-reduced-motion: reduce)')?.matches??false;}
 async load(url,pathUrl){const [response,pathResponse]=await Promise.all([fetch(url),fetch(pathUrl)]);if(!response.ok)throw Error(`Acupuncture data returned ${response.status}`);if(!pathResponse.ok)throw Error(`Acupuncture paths returned ${pathResponse.status}`);this.data=await response.json();this.surfacePaths=await pathResponse.json();if(this.surfacePaths.sourceSha256!==this.data.source.sha256)throw Error('Surface paths do not match the acupuncture source');this.rebuild();this.emit();return this.data.report;}
 setModel(model){this.model=model;this.selected=null;this.selectedKeys.clear();this.dragging=null;this.rebuild();this.emit();}
 setState({points=this.showPoints,lines=this.showLines,zones=this.showZones,labelChannel=this.labelChannel,dashed=this.dashed,channels=this.channels}={}){this.showPoints=Boolean(points);this.showLines=Boolean(lines);this.showZones=Boolean(zones);this.labelChannel=labelChannel||null;this.dashed=Boolean(dashed);this.channels=new Set(channels);this.rebuild();this.applyZoneVisibility();}
 setZoneRoot(root){if(this.zoneRoot){this.zoneRoot.traverse(object=>{object.geometry?.dispose();for(const material of Array.isArray(object.material)?object.material:object.material?[object.material]:[])material.dispose();});this.zoneRoot.removeFromParent();}this.zoneRoot=root;if(!root)return;root.traverse(object=>{if(!object.isMesh)return;const sourceMaterials=Array.isArray(object.material)?object.material:[object.material];object.material=sourceMaterials.map(material=>{const overlay=new THREE.MeshBasicMaterial({name:material.name,color:material.color,transparent:true,opacity:.52,depthTest:true,depthWrite:false,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-4,polygonOffsetUnits:-4});material.dispose();return overlay;});if(object.material.length===1)object.material=object.material[0];object.renderOrder=1;});this.zoneGroup.add(root);this.applyZoneVisibility();}
 applyZoneVisibility(){this.zoneRoot?.traverse(object=>{if(object.isMesh)object.visible=this.showZones&&this.channels.has(object.userData.channel);});}
 setEditing(value){this.editing=Boolean(value);this.dragging=null;this.rebuild();this.emit();}
 setCalibration(calibration){if(calibration?.sourceSha256&&calibration.sourceSha256!==this.data?.source?.sha256)throw Error('This calibration belongs to a different acupuncture source');this.overrides=cloneModels(calibration?.models);this.history=[];this.dirty=false;this.rebuild();this.emit();}
 exportCalibration(){return {schema:'acu-map-native-calibration',version:1,sourceSha256:this.data?.source?.sha256,updatedAt:new Date().toISOString(),models:cloneModels(this.overrides)};}
 markSaved(){this.dirty=false;this.emit();}
 emit(){this.onEditState({editing:this.editing,dirty:this.dirty,selectedKey:this.selected,canUndo:this.history.length>0,model:this.model,adjusted:Object.keys(this.overrides[this.model]||{}).length});}
 clear(){this.group.traverse(object=>{object.geometry?.dispose();if(object.userData.disposeMap)object.material?.map?.dispose();object.material?.dispose();});this.group.clear();this.pointObject=null;this.highlightObject=null;this.pointRecords=[];this.recordByKey.clear();}
 positionFor(key,point){const override=this.overrides[this.model]?.[key];return override?new THREE.Vector3(...override):nativePosition(point);}
 deltaFor(key){const override=this.overrides[this.model]?.[key],record=this.recordByKey.get(key);if(!override||!record)return new THREE.Vector3();return new THREE.Vector3(...override).sub(record.basePosition);}
 rebuild(){
  this.clear();if(!this.data||(!this.showPoints&&!this.showLines&&!this.showZones))return;
  const information=this.data.information;
  const records=this.data.points.filter(point=>point.model===this.model&&this.channels.has(point.channel)).map(point=>{const info=information[point.id]||{},key=`${point.id}:${point.side}`,basePosition=nativePosition(point),position=this.positionFor(key,point);return {...point,...info,key,basePosition,position};});
  for(const record of records)this.recordByKey.set(record.key,record);
  const visiblePaths=[];for(const [key,path] of Object.entries(this.surfacePaths?.models?.[this.model]?.paths||{})){const channelId=key.split(':')[0];if(!this.channels.has(channelId)||path.length<2)continue;const segments=[];let points=[];for(const sample of path){if(sample.breakBefore&&points.length){segments.push(points);points=[];}points.push(new THREE.Vector3(...sample.position).add(this.deltaFor(sample.from).lerp(this.deltaFor(sample.to),sample.mix)));}if(points.length)segments.push(points);visiblePaths.push({channelId,segments});}
  if(this.showLines){for(const {channelId,segments} of visiblePaths){for(const segment of segments){if(segment.length<2)continue;const geometry=new THREE.BufferGeometry().setFromPoints(segment),channel=CHANNELS.get(channelId),material=this.dashed?new THREE.LineDashedMaterial({color:channel.color,transparent:true,opacity:.92,depthTest:true,depthWrite:false,dashSize:.9,gapSize:.55}):new THREE.LineBasicMaterial({color:channel.color,transparent:true,opacity:.88,depthTest:true,depthWrite:false}),line=new THREE.Line(geometry,material);if(this.dashed)line.computeLineDistances();line.renderOrder=2;this.group.add(line);}}}
  if(this.showPoints&&records.length){const positions=[],colors=[];for(const record of records){positions.push(...record.position.toArray());const color=this.selectedKeys.has(record.key)?new THREE.Color('#00ff91'):CHANNELS.get(record.channel).color;colors.push(...color.toArray());}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const material=new THREE.PointsMaterial({size:this.editing?2.4:1.7,sizeAttenuation:true,vertexColors:true,map:this.pointTexture,alphaTest:.18,transparent:true,opacity:.98,depthTest:true,depthWrite:false});this.pointObject=new THREE.Points(geometry,material);this.pointObject.name='Acupoints';this.pointObject.renderOrder=3;this.group.add(this.pointObject);this.pointRecords=records;}
  if(this.showPoints&&(this.labelChannel||this.selectedKeys.size)){for(const record of records.filter(point=>(point.channel===this.labelChannel||this.selectedKeys.has(point.key))&&point.names?.chinese)){const {texture,aspect}=createLabelTexture(record.names.chinese),material=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false}),label=new THREE.Sprite(material),direction=record.side==='L'?-1:1;label.name=`Point label ${record.key}`;label.userData.disposeMap=true;label.position.copy(record.position).add(new THREE.Vector3(direction*.7,.25,.08));label.scale.set(2.05*aspect,2.05,1);label.center.set(record.side==='L'?1:0,.5);label.renderOrder=6;this.group.add(label);}}
  const highlighted=this.data.points.filter(point=>point.model===this.model&&this.highlightIds.has(point.id));
  if(highlighted.length){const positions=[];for(const point of highlighted){const key=`${point.id}:${point.side}`;positions.push(...this.positionFor(key,point).toArray());}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));const material=new THREE.PointsMaterial({size:2.85,sizeAttenuation:true,color:'#ff9f43',map:this.pointTexture,alphaTest:.1,transparent:true,opacity:1,depthTest:true,depthWrite:false,blending:THREE.AdditiveBlending});this.highlightObject=new THREE.Points(geometry,material);this.highlightObject.name='Prescription highlights';this.highlightObject.renderOrder=5;this.group.add(this.highlightObject);}
 }
 setHighlights(ids=[]){this.highlightIds=new Set(ids);this.rebuild();}
 animate(time=0){if(!this.highlightObject)return;const pulse=this.reduceMotion?1:.72+Math.sin(time*.0032)*.2;this.highlightObject.material.opacity=pulse;this.highlightObject.material.size=this.reduceMotion?3:2.75+Math.sin(time*.0032)*.38;}
 hitPoint(raycaster){if(!this.pointObject||!this.showPoints)return null;const previous=raycaster.params.Points.threshold;raycaster.params.Points.threshold=this.editing?.82:.62;const hit=raycaster.intersectObject(this.pointObject,false)[0];raycaster.params.Points.threshold=previous;return hit&&Number.isInteger(hit.index)?this.pointRecords[hit.index]:null;}
 describe(point,selection='single'){const channel=CHANNELS.get(point.channel),side=point.side==='M'?'Midline':point.side==='L'?'Left':'Right';return {acupoint:true,id:point.key,pointId:point.id,name:pointLabel(point,channel),compactLabel:pointLabel(point,channel),selection,side,region:`${titleCase(channel.name)} meridian · ${selection==='paired'?'Both sides':side}`,sections:point.sections||[],source:this.data.source};}
 search(query='',limit=100){
  if(!this.data)return [];
  const needle=query.trim().toLocaleLowerCase(),information=this.data.information;
  const unique=new Map();for(const point of this.data.points.filter(point=>point.model===this.model)){const info=information[point.id]||{},channel=CHANNELS.get(point.channel),key=`${point.id}:${point.side}`,terms=[point.id,point.channel,channel?.name,info.displayName,...Object.values(info.names||{})].filter(Boolean).join(' ').toLocaleLowerCase();if(!unique.has(point.id))unique.set(point.id,{...point,...info,key,channelName:channel?.name||point.channel,compactLabel:pointLabel({...point,...info},channel),terms});}
  const rows=[...unique.values()].filter(point=>!needle||point.terms.includes(needle));
  rows.sort((a,b)=>a.channel.localeCompare(b.channel)||a.number-b.number||a.side.localeCompare(b.side));
  return rows.slice(0,limit);
 }
 selectKey(key){
  if(!this.data)return null;
  const source=this.data.points.find(point=>point.model===this.model&&`${point.id}:${point.side}`===key);if(!source)return null;
  this.channels.add(source.channel);this.showPoints=true;this.selected=key;this.selectedKeys=new Set([key]);this.rebuild();const record=this.recordByKey.get(key);if(!record)return null;this.onSelect(this.describe(record,'single'));this.emit();return record;
 }
 selectPoint(id){
  if(!this.data)return [];
  const sources=this.data.points.filter(point=>point.model===this.model&&point.id===id);if(!sources.length)return [];
  this.channels.add(sources[0].channel);this.showPoints=true;this.selected=`${sources[0].id}:${sources[0].side}`;this.selectedKeys=new Set(sources.map(point=>`${point.id}:${point.side}`));this.rebuild();const records=sources.map(point=>this.recordByKey.get(`${point.id}:${point.side}`)).filter(Boolean);if(!records.length)return [];
  this.onSelect(this.describe(records[0],records.length>1?'paired':'single'));this.emit();return records;
 }
 pick(raycaster){const point=this.hitPoint(raycaster);if(!point)return null;this.selected=point.key;this.selectedKeys=new Set([point.key]);this.rebuild();this.emit();return this.describe(point,'single');}
 beginDrag(raycaster){if(!this.editing)return null;const point=this.hitPoint(raycaster);if(!point)return null;this.selected=point.key;this.selectedKeys=new Set([point.key]);const mirror=point.side==='L'?`${point.id}:R`:point.side==='R'?`${point.id}:L`:null,keys=[point.key,...(mirror?[mirror]:[])],before=Object.fromEntries(keys.map(key=>[key,this.overrides[this.model][key]?.slice()||null]));this.dragging={key:point.key,mirror,before,moved:false};this.rebuild();this.emit();this.onSelect(this.describe(point,'single'));return point;}
 surfacePoint(hit){if(!hit?.point)return null;const normal=hit.face?.normal?.clone().transformDirection(hit.object.matrixWorld)||new THREE.Vector3(0,0,1);return {position:hit.point.clone().addScaledVector(normal,SURFACE_OFFSET),normal};}
 mirrorSurface(position,normal,skinMeshes){const origin=position.clone();origin.x*=-1;const mirroredNormal=normal.clone();mirroredNormal.x*=-1;const caster=new THREE.Raycaster(origin.clone().addScaledVector(mirroredNormal,3),mirroredNormal.clone().negate(),0,6),hit=caster.intersectObjects(skinMeshes,false)[0];return hit?this.surfacePoint(hit).position:origin;}
 dragTo(hit,skinMeshes){if(!this.dragging)return false;const surface=this.surfacePoint(hit);if(!surface)return false;this.overrides[this.model][this.dragging.key]=surface.position.toArray();if(this.dragging.mirror)this.overrides[this.model][this.dragging.mirror]=this.mirrorSurface(surface.position,surface.normal,skinMeshes).toArray();this.dragging.moved=true;this.dirty=true;this.rebuild();this.emit();return true;}
 endDrag(cancel=false){if(!this.dragging)return false;const drag=this.dragging;this.dragging=null;if(cancel){for(const [key,value] of Object.entries(drag.before))value?this.overrides[this.model][key]=value:delete this.overrides[this.model][key];this.rebuild();this.emit();return false;}if(drag.moved)this.history.push({model:this.model,before:drag.before});this.emit();return drag.moved;}
 undo(){const action=this.history.pop();if(!action)return false;for(const [key,value] of Object.entries(action.before))value?this.overrides[action.model][key]=value:delete this.overrides[action.model][key];this.dirty=true;this.rebuild();this.emit();return true;}
 resetSelected(){if(!this.selected)return false;const [id,side]=this.selected.split(':'),keys=[this.selected,...(side==='L'?[`${id}:R`]:side==='R'?[`${id}:L`]:[])],before=Object.fromEntries(keys.map(key=>[key,this.overrides[this.model][key]?.slice()||null]));let changed=false;for(const key of keys)if(this.overrides[this.model][key]){delete this.overrides[this.model][key];changed=true;}if(changed){this.history.push({model:this.model,before});this.dirty=true;this.rebuild();this.emit();}return changed;}
 resetModel(){const keys=Object.keys(this.overrides[this.model]);if(!keys.length)return false;const before=Object.fromEntries(keys.map(key=>[key,this.overrides[this.model][key].slice()]));this.history.push({model:this.model,before});this.overrides[this.model]={};this.dirty=true;this.rebuild();this.emit();return true;}
 dispose(){this.clear();this.setZoneRoot(null);this.pointTexture.dispose();this.zoneGroup.removeFromParent();this.group.removeFromParent();}
}
