import {ViewerEngine} from './viewer-engine.js';
import {readJson,defaultSystems,activeNodes} from './scene-data.js';
import {ACUPUNCTURE_CHANNELS} from './acupuncture-layer.js';
import './style.css';
import './dock.css';
const $=id=>document.getElementById(id);
document.querySelector('.explore-content').prepend($('selection-actions').content.cloneNode(true));
let engine,manifest,model,display,systemState,selected=null,busy=false,bodyMapBusy=false,region='Full body',visibleIds=new Set(),isolation=null,hidden=new Set(),fatal=false,heartMotion=true,drawingDraft=null,drawingViewMode=false,loadedDrawing=null,toastTimer,pendingDrawingKind='drawing',activeMeshBand='ST',meshLayerVisibility=new Map(),surfaceState={selectedSurface:false,selectedVertex:false,vertexCount:0,surfaceTool:'surface',curvedVertex:false},showAcupoints=true,showMeridians=true,acupunctureChannels=new Set(ACUPUNCTURE_CHANNELS.map(([id])=>id)),acupunctureEditState={editing:false,dirty:false,selectedKey:null,canUndo:false,model:'Male',adjusted:0};
const DRAWINGS_KEY='anatomy-skin-drawings-v1';
const ACUPUNCTURE_CALIBRATION_KEY='anatomy-acupuncture-calibration-v1';
const BRUSH_SIZE_KEY='anatomy-brush-size-v2',BRUSH_COLOR_KEY='anatomy-brush-color-v1',BRUSH_SIZES=[{label:'Finest',scale:.44},{label:'Extra fine',scale:.58},{label:'Fine',scale:.72},{label:'Small',scale:.86},{label:'Medium',scale:1}],BRUSH_COLORS=['#ff6b62','#3d8bff','#32c76f','#ffd43b','#f5f7fa','#1a1a1a'];
const BODY_MAP_BANDS=[['ST','Stomach','#f6ec26'],['SP','Spleen','#f97b08'],['HT','Heart','#7002a9'],['SI','Small intestine','#9256e6'],['BL','Bladder','#1b4cfc'],['KD','Kidney','#020db3'],['PC','Pericardium','#a90002'],['TW','Triple warmer','#f00101'],['GB','Gallbladder','#3dd30e'],['LR','Liver','#1c7d09'],['LU','Lung','#b5c3c2'],['LI','Large intestine','#fcfcfc']],bodyMapBands=new Set();
let textureLevel='original';try{if(localStorage.getItem('anatomy-texture')==='balanced')textureLevel='balanced';}catch{}
const APK_SYSTEM_ICON={Skeletal:'skeletal','Connective T.':'connective-t',Muscular:'muscular',Arterial:'arterial',Venous:'venous',Lymphatic:'lymphatic',Nervous:'nervous',Respiratory:'respiratory',Digestive:'digestive',Endocrine:'endocrine',Urogenital:'urogenital',Integumentary:'integumentary'};
$('texture').value=textureLevel;
function status(text,error=false){$('loading').hidden=false;$('load-text').textContent=text;$('retry').hidden=!error;$('progress').hidden=error;}
function lock(value){busy=value;if(engine)engine.busy=value;for(const control of document.querySelectorAll('#model,#area,#texture,#regions button,#systems button,#system-actions button,.structure,.model-toggle button,#create-drawing,#create-colour-mesh,#load-drawing,#body-map-bands button,#body-map-all,#body-map-clear,#acupuncture-menu button'))control.disabled=value||control.dataset.unavailable==='true';$('isolate').disabled=$('hide').disabled=value||!selected||selected?.acupoint;$('restore').disabled=value||!engine?.root;}
function setSelectionDrawer(open){const drawer=$('selection-drawer'),toggle=$('selection-toggle');drawer.classList.toggle('is-open',open);drawer.setAttribute('aria-hidden',String(!open));toggle.setAttribute('aria-expanded',String(open));requestAnimationFrame(()=>engine?.updateViewport());}
function selection(record){if(record&&!record.acupoint)return;selected=record;const acupoint=record?.acupoint;$('selected-name').textContent=record?.name||'Choose a point';$('selected-meta').textContent=record?`${record.region} · Source review pending`:'Tap a colored point on the model to read its reference information.';$('isolate').disabled=$('hide').disabled=true;if(record)setSelectionDrawer(true);
 const info=acupoint?record:display?.info?.[record?.cid];$('selected-latin').textContent=info?.latin||'';$('selected-info').replaceChildren();
 for(const section of info?.sections||[]){const heading=document.createElement('h3'),text=document.createElement('p');heading.textContent=section.name;text.textContent=(section.text||'').replace(/\\n/g,'\n');$('selected-info').append(heading,text);}
 if(acupoint){const provenance=document.createElement('p');provenance.className='source-note';provenance.textContent='Extracted from the supplied 免费找穴位神器 APK and projected onto this model’s skin. Anatomical placement and clinical content remain pending practitioner review.';$('selected-info').append(provenance);}else if(record&&!info?.sections?.length)$('selected-info').textContent='No description is included for this structure in the recovered library.';
}
function drawings(){try{const value=JSON.parse(localStorage.getItem(DRAWINGS_KEY)||'[]');return Array.isArray(value)?value:[];}catch{return [];}}
function writeDrawings(items){localStorage.setItem(DRAWINGS_KEY,JSON.stringify(items));}
function drawingId(){return globalThis.crypto?.randomUUID?.()||`drawing-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function closeMenus(){for(const menu of document.querySelectorAll('.floating-tools details'))menu.open=false;}
function toast(message){clearTimeout(toastTimer);$('drawing-toast').textContent=message;$('drawing-toast').hidden=false;toastTimer=setTimeout(()=>$('drawing-toast').hidden=true,2600);}
function setBrushSize(value){const index=Math.min(BRUSH_SIZES.length-1,Math.max(0,Number(value)-1)),size=BRUSH_SIZES[index];$('brush-size').value=String(index+1);$('brush-size').setAttribute('aria-valuetext',size.label);$('brush-size-value').textContent=size.label;engine?.setDrawingBrushScale(size.scale);try{localStorage.setItem(BRUSH_SIZE_KEY,String(index+1));}catch{}}
function setBrushColor(value){const color=BRUSH_COLORS.includes(value)?value:BRUSH_COLORS[0];for(const button of document.querySelectorAll('[data-brush-color]'))button.setAttribute('aria-pressed',String(button.dataset.brushColor===color));engine?.setDrawingColor(color);try{localStorage.setItem(BRUSH_COLOR_KEY,color);}catch{}}
function meshBand(id=activeMeshBand){return BODY_MAP_BANDS.find(([bandId])=>bandId===id)||BODY_MAP_BANDS[0];}
function renderMeshBandButtons(){const container=$('mesh-band-buttons');container.replaceChildren();for(const [id,name,color] of BODY_MAP_BANDS){const button=document.createElement('button');button.type='button';button.dataset.meshBand=id;button.style.setProperty('--swatch',color);button.setAttribute('aria-label',`${id} ${name} layer`);button.setAttribute('aria-pressed',String(id===activeMeshBand));button.innerHTML=`<i></i><span>${id}</span>`;button.onclick=()=>setMeshBand(id);container.append(button);}}
function setMeshBand(id){const band=meshBand(id);activeMeshBand=band[0];meshLayerVisibility.set(activeMeshBand,true);engine?.setDrawingBand(...band);engine?.setDrawingLayerVisible(activeMeshBand,true);for(const button of document.querySelectorAll('[data-mesh-band]'))button.setAttribute('aria-pressed',String(button.dataset.meshBand===activeMeshBand));if(drawingDraft?.kind==='colour-mesh'&&!drawingViewMode)$('drawing-status').textContent=`${band[0]} · ${band[1]} · Drag across any visible skin areas to create a surface.`;renderMeshLayers();}
function renderMeshLayers(stats=engine?.drawingLayerStats?.()||{}){const list=$('mesh-layer-list');list.replaceChildren();let used=0;for(const [id,name,color] of BODY_MAP_BANDS){const count=stats[id]||0;if(count)used++;const row=document.createElement('div'),select=document.createElement('button'),visibility=document.createElement('button');row.className='mesh-layer-row';row.style.setProperty('--swatch',color);select.type='button';select.dataset.layerSelect=id;select.setAttribute('aria-pressed',String(id===activeMeshBand));select.innerHTML=`<i></i><span><strong>${id}</strong><small>${name} · ${count} surface${count===1?'':'s'}</small></span>`;select.onclick=()=>setMeshBand(id);const visible=meshLayerVisibility.get(id)!==false;visibility.type='button';visibility.dataset.layerVisibility=id;visibility.setAttribute('aria-pressed',String(visible));visibility.setAttribute('aria-label',`${visible?'Hide':'Show'} ${id} layer`);visibility.textContent=visible?'Shown':'Hidden';visibility.onclick=()=>{const next=meshLayerVisibility.get(id)===false;meshLayerVisibility.set(id,next);engine?.setDrawingLayerVisible(id,next);renderMeshLayers();};row.append(select,visibility);list.append(row);}$('mesh-layer-count').textContent=`${used}/12`;}
function setDrawingKindUI(kind){const mesh=kind==='colour-mesh';$('mesh-band-colors').hidden=!mesh;$('mesh-layer-menu').hidden=!mesh;$('surface-edit-controls').hidden=!mesh;document.querySelector('.brush-colors').hidden=mesh;$('drawing-toolbar').classList.toggle('colour-mesh-mode',mesh);$('undo-drawing').textContent=mesh?'Undo surface':'Undo stroke';if(mesh){renderMeshBandButtons();renderMeshLayers();setMeshBand(activeMeshBand);}}
function renderBodyMap(){const container=$('body-map-bands');container.replaceChildren();for(const [id,name,color] of BODY_MAP_BANDS){const button=document.createElement('button'),dot=document.createElement('i'),copy=document.createElement('span');button.type='button';button.dataset.band=id;button.setAttribute('aria-pressed',String(bodyMapBands.has(id)));button.setAttribute('aria-label',`${id}, ${name}`);dot.style.setProperty('--band-color',color);copy.innerHTML=`<strong>${id}</strong><small>${name}</small>`;button.append(dot,copy);button.onclick=()=>{if(bodyMapBusy||busy)return;bodyMapBands.has(id)?bodyMapBands.delete(id):bodyMapBands.add(id);applyBodyMap();};container.append(button);}$('body-map-count').textContent=bodyMapBands.size?`${bodyMapBands.size}/12`:'Off';}
function renderAcupuncture(){const container=$('acupuncture-channels');container.replaceChildren();for(const [id,name,color] of ACUPUNCTURE_CHANNELS){const button=document.createElement('button'),dot=document.createElement('i'),label=document.createElement('span');button.type='button';button.dataset.channel=id;button.style.setProperty('--channel-color',color);button.setAttribute('aria-pressed',String(acupunctureChannels.has(id)));button.setAttribute('aria-label',`${id}, ${name}`);dot.setAttribute('aria-hidden','true');label.textContent=`${id} · ${name}`;button.append(dot,label);button.onclick=()=>{acupunctureChannels.has(id)?acupunctureChannels.delete(id):acupunctureChannels.add(id);applyAcupuncture();};container.append(button);}$('acupuncture-points').setAttribute('aria-pressed',String(showAcupoints));$('acupuncture-lines').setAttribute('aria-pressed',String(showMeridians));$('acupuncture-count').textContent=!showAcupoints&&!showMeridians?'Off':`${showAcupoints?'P':''}${showAcupoints&&showMeridians?' · ':''}${showMeridians?'L':''}`;}
function applyAcupuncture(){renderAcupuncture();engine?.setAcupuncture({points:showAcupoints,lines:showMeridians,channels:acupunctureChannels});}
function acupunctureEditEvent(state){acupunctureEditState=state;const edit=$('acupuncture-edit');if(!edit)return;edit.setAttribute('aria-pressed',String(state.editing));edit.textContent=state.editing?'Finish editing':'Edit points';$('acupuncture-save').disabled=!state.dirty;$('acupuncture-undo').disabled=!state.canUndo;$('acupuncture-reset-point').disabled=!state.selectedKey;$('acupuncture-reset-model').disabled=!state.adjusted;const selected=state.selectedKey?` · ${state.selectedKey}`:'',changed=state.dirty?' · unsaved':'';$('acupuncture-edit-status').textContent=state.editing?`${state.adjusted} adjusted${selected}${changed}. Drag points on visible skin.`:`${state.adjusted} adjusted for ${state.model}${changed}.`;}
function saveAcupunctureCalibration(){try{localStorage.setItem(ACUPUNCTURE_CALIBRATION_KEY,JSON.stringify(engine.exportAcupunctureCalibration()));engine.markAcupunctureSaved();toast('Acupuncture calibration saved on this device');return true;}catch(error){toast(`Calibration could not be saved: ${error.message}`);return false;}}
function downloadAcupunctureCalibration(){const data=engine.exportAcupunctureCalibration(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`anatomy-acupuncture-calibration-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function skinLayerIndex(system){return Math.max(0,system?.layers.findIndex(layer=>layer.nodeIds.some(id=>/^Skin\b/i.test(display?.nodeInfo[id]?.name||'')))??0);}
async function applyBodyMap(){renderBodyMap();if(!engine?.parser||busy||bodyMapBusy)return;bodyMapBusy=true;for(const control of document.querySelectorAll('#body-map-bands button,#body-map-all,#body-map-clear'))control.disabled=true;try{const skin=display.systems.find(system=>system.name==='Integumentary'),state=systemState[skin?.id],skinLevel=skinLayerIndex(skin),needsBase=bodyMapBands.size&&state&&(!state.enabled||state.level!==skinLevel);if(needsBase){state.enabled=true;state.level=skinLevel;renderSystems();await refresh();}else{engine.setBodyMapBands(bodyMapBands);await engine.refreshBodyMap();}}catch(error){toast(`Body map could not update: ${error.message}`);}finally{bodyMapBusy=false;for(const control of document.querySelectorAll('#body-map-bands button,#body-map-all,#body-map-clear'))control.disabled=false;}}
function drawingEvent(event){
 if(event.type==='miss'){$('drawing-status').textContent=event.reason==='band'?'Choose a body layer before painting.':event.reason==='surface'?'Select a surface before adding a vertex.':'Skin only — begin on visible skin.';return;}
 if(event.type==='changed'&&drawingDraft){
  const has=engine?.hasDrawing();surfaceState={...surfaceState,...event};$('undo-drawing').disabled=drawingViewMode||!has;$('save-drawing').disabled=!has;updateSurfaceControls(surfaceState);
  if(drawingDraft.kind==='colour-mesh')renderMeshLayers(event.layerStats);
  if(!drawingViewMode){
   const band=meshBand();
   if(drawingDraft.kind==='colour-mesh')$('drawing-status').textContent=event.surfaceTool==='add-vertex'?`${band[0]} · Tap any visible skin area to insert the new vertex.`:event.selectedSurface?`${band[0]} · ${event.vertexCount} vertices · Drag anchors or curve handles; drag inside to move.`:`${band[0]} · ${band[1]} · ${event.strokeCount} surface${event.strokeCount===1?'':'s'} · Drag across skin areas to create.`;
   else $('drawing-status').textContent=has?`${event.strokeCount} stroke${event.strokeCount===1?'':'s'} · Stylus draws; fingers navigate.`:'Stylus draws on skin · fingers rotate, pan, and zoom.';
  }
 }
}
function updateSurfaceControls(state=surfaceState){const locked=drawingViewMode||!state.selectedSurface;$('surface-add-vertex').disabled=locked;$('surface-add-vertex').setAttribute('aria-pressed',String(!drawingViewMode&&state.surfaceTool==='add-vertex'));$('surface-delete-vertex').disabled=locked||!state.selectedVertex||state.vertexCount<=3;$('surface-curve').disabled=locked||!state.selectedVertex;$('surface-curve').textContent=state.curvedVertex?'Make corner':'Make curve';for(const id of ['surface-smaller','surface-larger','delete-surface'])$(id).disabled=locked;}
async function ensureSkinVisible(){const skin=display?.systems.find(system=>system.name==='Integumentary');if(!skin)return;const state=systemState[skin.id],skinLevel=skinLayerIndex(skin);if(!state.enabled||state.level!==skinLevel){state.enabled=true;state.level=skinLevel;renderSystems();await refresh();}}
function setDrawingViewMode(viewing){if(!drawingDraft)return;drawingViewMode=Boolean(viewing);document.body.classList.toggle('drawing-mode',!drawingViewMode);document.body.classList.toggle('drawing-view-mode',drawingViewMode);$('drawing-view-mode').setAttribute('aria-pressed',String(drawingViewMode));$('drawing-view-mode').setAttribute('aria-label',drawingViewMode?'Return to editable drawing mode':'View drawing without editing');$('drawing-view-mode').title=drawingViewMode?'Return to drawing mode':'View mode';$('brush-size').disabled=drawingViewMode;for(const button of document.querySelectorAll('[data-brush-color],[data-mesh-band]'))button.disabled=drawingViewMode;$('undo-drawing').disabled=drawingViewMode||!engine?.hasDrawing();updateSurfaceControls(engine?.surfaceEditState?.()||surfaceState);if(drawingViewMode)$('drawing-status').textContent='View mode · body layers are visible but not editable.';else if(drawingDraft.kind==='colour-mesh'){const band=meshBand();$('drawing-status').textContent=`${band[0]} · ${band[1]} · Drag across any visible skin areas to create a surface.`;}else $('drawing-status').textContent='Stylus draws on skin · fingers rotate, pan, and zoom.';if(drawingViewMode)engine?.stopDrawing();else engine?.startDrawing();}
function stopDrawing({clear=false}={}){engine?.stopDrawing();document.body.classList.remove('drawing-mode','drawing-view-mode');$('drawing-toolbar').hidden=true;$('brush-size').disabled=false;for(const button of document.querySelectorAll('[data-brush-color],[data-mesh-band]'))button.disabled=false;$('drawing-view-mode').setAttribute('aria-pressed','false');drawingViewMode=false;drawingDraft=null;if(clear)engine?.clearDrawing();}
function renderDrawingLibrary(){
 const list=$('drawing-list'),items=drawings().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));list.replaceChildren();
 if(!items.length){const empty=document.createElement('div');empty.className='drawing-empty';empty.innerHTML='<strong>No saved drawings</strong><p>Create a skin drawing and it will appear here.</p>';list.append(empty);return;}
 for(const item of items){const row=document.createElement('article'),copy=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('span'),actions=document.createElement('div'),load=document.createElement('button'),remove=document.createElement('button'),mesh=item.kind==='colour-mesh';row.className='drawing-file';name.textContent=`${item.name}.${mesh?'bodymesh':'drawing'}`;meta.textContent=`${item.modelLabel} · ${mesh?'12-colour body layers':'Skin drawing'} · ${new Date(item.updatedAt).toLocaleString()}`;copy.append(name,meta);load.textContent='Load';load.onclick=()=>loadSavedDrawing(item);remove.textContent='Delete';remove.className='danger';remove.onclick=()=>{if(!confirm(`Delete “${item.name}”?`))return;writeDrawings(drawings().filter(saved=>saved.id!==item.id));if(loadedDrawing?.id===item.id){engine.clearDrawing();loadedDrawing=null;$('close-drawing').hidden=true;}renderDrawingLibrary();};actions.append(load,remove);row.append(copy,actions);list.append(row);}
}
async function loadSavedDrawing(item){$('drawing-library-dialog').close();if(model.id!==item.modelId)await switchModel(item.modelId);await ensureSkinVisible();engine.setDrawingMode(item.kind||'drawing');engine.loadDrawing(item.strokes);meshLayerVisibility=new Map(Object.entries(item.layerVisibility||{}));for(const [id,visible] of meshLayerVisibility)engine.setDrawingLayerVisible(id,visible);loadedDrawing=item;$('close-drawing').hidden=false;toast(`Loaded ${item.name}.${item.kind==='colour-mesh'?'bodymesh':'drawing'}`);}
function desired(){const result=activeNodes(display.systems,systemState);for(const id of result){const record=engine.records.get(id);if(!record||(region!=='Full body'&&record.region!==region)||hidden.has(id)||(isolation!==null&&isolation!==id))result.delete(id);}return result;}
function list(){
 const query=$('search').value.trim(),rows=engine?.searchAcupuncture(query,100)||[];
 $('count').textContent=`${rows.length.toLocaleString()} point${rows.length===1?'':'s'}${rows.length===100?' · refine your search':''}`;
 $('structures').replaceChildren();for(const row of rows){const button=document.createElement('button'),name=document.createElement('strong'),meta=document.createElement('small'),side=document.createElement('span');button.className='structure';name.textContent=`${row.id} · ${row.displayName||row.id}${row.chineseSimplified?` / ${row.chineseSimplified}`:''}`;meta.textContent=`${row.channelName} meridian`;side.className='point-side';side.textContent=row.side==='M'?'Midline':row.side==='L'?'Left':'Right';button.append(name,meta,side);button.disabled=busy;button.onclick=()=>{showAcupoints=true;acupunctureChannels.add(row.channel);applyAcupuncture();engine.focusAcupuncture(row.key);closeMenus();};$('structures').append(button);}
 if(!rows.length)$('structures').textContent='No matching point. Try a code such as LI4 or a Chinese, English, Korean, or pinyin name.';
 $('empty-scene').hidden=visibleIds.size>0||busy;
}
async function refresh({fit=false,front=false}={}){
 if(busy||!engine?.parser)return;lock(true);$('empty-scene').hidden=true;const ids=desired();
 const missing=[...ids].some(id=>!engine.loaded.has(id));if(missing){status('Loading selected systems…');$('progress').removeAttribute('value');}
 try{const previous=selected?.id;engine.select(null);await engine.show(ids,(done,total)=>{$('load-text').textContent=`Loading structures · ${done} / ${total}`;$('progress').max=total;$('progress').value=done;});const overlays=display.systems.flatMap(s=>systemState[s.id].enabled?s.layers[systemState[s.id].level].overlayIds:[]);engine.setBodyMapBands(bodyMapBands);await engine.overlays.apply([...new Set(overlays)]);visibleIds=ids;if(ids.has(previous))engine.select(previous);$('loading').hidden=true;if(fit)engine.fit(front?[0,0,1]:undefined);}
 catch(error){status(`Unable to load the selected systems. ${error.message}`,true);}
 finally{lock(false);list();}
}
function renderSystems(){
 $('systems').replaceChildren();
 for(const system of display.systems){
  const value=systemState[system.id],button=document.createElement('button'),name=document.createElement('strong'),levelLabel=document.createElement('span'),fraction=`${value.level+1}/${system.layers.length}`,level=value.enabled?fraction:'—',detail=value.enabled?`${system.layers[value.level].name} · ${fraction}`:'Off';button.className='system-button';button.dataset.system=system.name;button.setAttribute('aria-pressed',String(value.enabled));name.textContent=system.name;levelLabel.textContent=level;button.append(name,levelLabel);button.setAttribute('title',`${system.name}: ${detail}`);button.setAttribute('aria-label',`${system.name}: ${detail}. Tap for next level.`);
  button.onclick=()=>{if(busy)return;if(!value.enabled){value.enabled=true;value.level=0;}else if(value.level+1<system.layers.length)value.level++;else{value.enabled=false;value.level=0;}isolation=null;renderSystems();refresh();};$('systems').append(button);
 }
}
function renderRegions(){
 $('regions').replaceChildren();$('area').replaceChildren();for(const name of ['Full body',...model.regions.map(r=>r.name)]){const option=document.createElement('option');option.value=name;option.textContent=name;$('area').append(option);const button=document.createElement('button');button.textContent=name;button.setAttribute('aria-pressed',String(name===region));button.onclick=()=>{if(busy)return;region=name;$('area').value=name;$('region-title').textContent=region;isolation=null;renderRegions();refresh({fit:true});};$('regions').append(button);}$('area').value=region;
}
function acupunctureDefaultSystems(systems){const state=Object.fromEntries(systems.map(system=>[system.id,{enabled:false,level:system.defaultLayer}])),skin=systems.find(system=>system.name==='Integumentary');if(skin){state[skin.id].enabled=true;state[skin.id].level=skinLayerIndex(skin);}return state;}
async function loadModel(resetSystems=true){
 if(busy)return;lock(true);status(`Preparing ${model.label.toLowerCase()}…`);$('progress').removeAttribute('value');visibleIds=new Set();hidden.clear();isolation=null;engine.release();list();
 try{
  display=await readJson(model.displayUrl);if(resetSystems||!systemState)systemState=acupunctureDefaultSystems(display.systems);
  renderSystems();renderRegions();lock(true);$('region-title').textContent=region;
  await engine.prepare(model,display,textureLevel);lock(false);await refresh({fit:true,front:true});
 }catch(error){status(`Viewer could not load the model. ${error.message}`,true);lock(false);}
}
async function switchModel(id){model=manifest.models.find(item=>item.id===id);$('model').value=model.id;$('model-male').setAttribute('aria-pressed',String(model.id==='Male'));$('model-female').setAttribute('aria-pressed',String(model.id==='Female'));loadedDrawing=null;$('close-drawing').hidden=true;await loadModel(true);}
$('texture').onchange=()=>{textureLevel=$('texture').value;try{localStorage.setItem('anatomy-texture',textureLevel);}catch{}loadModel(false);};
$('isolate').onclick=()=>{if(!selected||busy)return;isolation=selected.id;refresh({fit:true});};
$('hide').onclick=()=>{if(!selected||busy)return;hidden.add(selected.id);engine.select(null);refresh();};
$('restore').onclick=()=>{if(busy)return;hidden.clear();isolation=null;engine.select(null);refresh({fit:true});};
$('all-systems').onclick=()=>{if(busy)return;for(const value of Object.values(systemState))value.enabled=true;isolation=null;hidden.clear();renderSystems();refresh();};
$('no-systems').onclick=()=>{if(busy)return;for(const value of Object.values(systemState))value.enabled=false;isolation=null;renderSystems();refresh();};
$('default-systems').onclick=()=>{if(busy)return;systemState=acupunctureDefaultSystems(display.systems);isolation=null;hidden.clear();renderSystems();refresh({fit:true,front:true});};
function openDrawingDialog(kind){pendingDrawingKind=kind;const mesh=kind==='colour-mesh';closeMenus();$('drawing-name-title').textContent=mesh?'Create colour surfaces':'Create drawing';$('drawing-name-help').textContent=mesh?'Drag a surface across any visible skin sections. Add or delete anchor vertices, convert anchors between corners and curves, and drag Bézier handles to shape the boundary. The colour remains a flat skin display layer.':'Use the stylus to draw on visible skin. Use fingers normally to rotate, pan, and pinch to zoom.';$('start-drawing').textContent=mesh?'Start surfaces':'Start drawing';$('drawing-name').value=mesh?`Body map ${drawings().filter(item=>item.kind==='colour-mesh').length+1}`:`Skin drawing ${drawings().filter(item=>item.kind!=='colour-mesh').length+1}`;$('drawing-name-dialog').showModal();requestAnimationFrame(()=>$('drawing-name').select());}
$('create-drawing').onclick=()=>openDrawingDialog('drawing');
$('create-colour-mesh').onclick=()=>openDrawingDialog('colour-mesh');
$('load-drawing').onclick=()=>{closeMenus();renderDrawingLibrary();$('drawing-library-dialog').showModal();};
$('close-drawing').onclick=()=>{engine.clearDrawing();loadedDrawing=null;$('close-drawing').hidden=true;closeMenus();toast('Drawing closed');};
$('cancel-drawing-name').onclick=()=>$('drawing-name-dialog').close();
$('close-drawing-library').onclick=()=>$('drawing-library-dialog').close();
$('body-map-all').onclick=()=>{if(bodyMapBusy||busy)return;BODY_MAP_BANDS.forEach(([id])=>bodyMapBands.add(id));applyBodyMap();};
$('body-map-clear').onclick=()=>{if(bodyMapBusy||busy)return;bodyMapBands.clear();applyBodyMap();};
$('acupuncture-points').onclick=()=>{showAcupoints=!showAcupoints;applyAcupuncture();};
$('acupuncture-lines').onclick=()=>{showMeridians=!showMeridians;applyAcupuncture();};
$('acupuncture-all').onclick=()=>{acupunctureChannels=new Set(ACUPUNCTURE_CHANNELS.map(([id])=>id));applyAcupuncture();};
$('acupuncture-clear').onclick=()=>{acupunctureChannels.clear();applyAcupuncture();};
$('acupuncture-edit').onclick=async()=>{const editing=!acupunctureEditState.editing;if(editing){await ensureSkinVisible();showAcupoints=true;if(!acupunctureChannels.size)acupunctureChannels=new Set(ACUPUNCTURE_CHANNELS.map(([id])=>id));applyAcupuncture();}engine.setAcupunctureEditing(editing);if(editing){setSelectionDrawer(false);closeMenus();toast('Drag a point across the skin; its paired side mirrors automatically');}};
$('acupuncture-save').onclick=saveAcupunctureCalibration;
$('acupuncture-undo').onclick=()=>engine.undoAcupuncture();
$('acupuncture-reset-point').onclick=()=>{if(!engine.resetSelectedAcupuncture())toast('This point has no saved adjustment to reset');};
$('acupuncture-reset-model').onclick=()=>{if(confirm(`Reset every adjusted point on the ${model.label.toLowerCase()} model?`))engine.resetAcupunctureModel();};
$('acupuncture-export').onclick=downloadAcupunctureCalibration;
$('acupuncture-import').onclick=()=>$('acupuncture-import-file').click();
$('acupuncture-import-file').onchange=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const calibration=JSON.parse(await file.text());engine.setAcupunctureCalibration(calibration);saveAcupunctureCalibration();toast(`Imported ${file.name}`);}catch(error){toast(`Calibration import failed: ${error.message}`);}};
$('brush-size').oninput=event=>setBrushSize(event.target.value);
for(const button of document.querySelectorAll('[data-brush-color]'))button.onclick=()=>setBrushColor(button.dataset.brushColor);
$('drawing-view-mode').onclick=()=>setDrawingViewMode(!drawingViewMode);
$('surface-add-vertex').onclick=()=>engine.setSurfaceTool(surfaceState.surfaceTool==='add-vertex'?'surface':'add-vertex');
$('surface-delete-vertex').onclick=()=>engine.deleteSelectedSurfaceVertex();
$('surface-curve').onclick=()=>engine.toggleSelectedSurfaceCurve();
$('surface-smaller').onclick=()=>engine.resizeSelectedSurface(.82);
$('surface-larger').onclick=()=>engine.resizeSelectedSurface(1.22);
$('delete-surface').onclick=()=>engine.deleteSelectedSurface();
$('drawing-name-form').onsubmit=async event=>{event.preventDefault();const name=$('drawing-name').value.trim();if(!name)return;$('drawing-name-dialog').close();await ensureSkinVisible();engine.clearDrawing();engine.setDrawingMode(pendingDrawingKind);meshLayerVisibility=new Map(BODY_MAP_BANDS.map(([id])=>[id,true]));drawingDraft={id:drawingId(),name,kind:pendingDrawingKind,modelId:model.id,modelLabel:model.label,createdAt:new Date().toISOString()};loadedDrawing=null;$('close-drawing').hidden=true;setSelectionDrawer(false);closeMenus();$('drawing-title').textContent=name;$('undo-drawing').disabled=true;$('save-drawing').disabled=true;setDrawingKindUI(pendingDrawingKind);$('drawing-toolbar').hidden=false;if(pendingDrawingKind==='colour-mesh')setMeshBand(activeMeshBand);setDrawingViewMode(false);};
$('undo-drawing').onclick=()=>engine.undoDrawing();
$('cancel-drawing').onclick=()=>stopDrawing({clear:true});
$('save-drawing').onclick=()=>{const strokes=engine.exportDrawing();if(!drawingDraft||!strokes.length)return;const now=new Date().toISOString(),record={...drawingDraft,updatedAt:now,strokes,layerVisibility:drawingDraft.kind==='colour-mesh'?Object.fromEntries(meshLayerVisibility):undefined},items=drawings(),index=items.findIndex(item=>item.id===record.id);if(index>=0)items[index]=record;else items.push(record);try{writeDrawings(items);}catch{$('drawing-status').textContent='Could not save. Tablet storage for drawings is full.';return;}engine.stopDrawing();document.body.classList.remove('drawing-mode','drawing-view-mode');$('drawing-toolbar').hidden=true;$('brush-size').disabled=false;for(const button of document.querySelectorAll('[data-brush-color],[data-mesh-band]'))button.disabled=false;drawingViewMode=false;drawingDraft=null;loadedDrawing=record;$('close-drawing').hidden=false;toast(`Saved ${record.name}.${record.kind==='colour-mesh'?'bodymesh':'drawing'}`);};
$('heart-motion').onclick=()=>{heartMotion=!heartMotion;engine?.setHeartMotion(heartMotion);$('heart-motion').textContent=`Heart: ${heartMotion?'On':'Off'}`;$('heart-motion').setAttribute('aria-pressed',String(heartMotion));$('heart-motion').setAttribute('aria-label',heartMotion?'Pause heart motion':'Play heart motion');};$('fit').onclick=()=>engine?.fit();$('front').onclick=()=>engine?.fit([0,0,1]);$('back').onclick=()=>engine?.fit([0,0,-1]);$('selection-toggle').onclick=()=>setSelectionDrawer(!$('selection-drawer').classList.contains('is-open'));$('close-selection').onclick=()=>setSelectionDrawer(false);$('search').oninput=list;
$('retry').onclick=()=>{if(fatal||!manifest){location.reload();return;}if(engine?.parser)refresh({fit:true});else loadModel(false);};
async function start(){try{
 $('selection-drawer').append($('selection-actions').content.cloneNode(true));engine=new ViewerEngine($('canvas'),selection,()=>{fatal=true;status('Graphics memory was exhausted. Reload the viewer to continue.',true);},drawingEvent,acupunctureEditEvent);engine.setHeartMotion(heartMotion);await engine.loadAcupuncture('acupuncture-data.json','acupuncture-registration.json');applyAcupuncture();list();let savedBrushSize=5,savedBrushColor=BRUSH_COLORS[0];try{savedBrushSize=Number(localStorage.getItem(BRUSH_SIZE_KEY))||5;savedBrushColor=localStorage.getItem(BRUSH_COLOR_KEY)||BRUSH_COLORS[0];const savedCalibration=JSON.parse(localStorage.getItem(ACUPUNCTURE_CALIBRATION_KEY)||'null');if(savedCalibration)engine.setAcupunctureCalibration(savedCalibration);}catch{}setBrushSize(savedBrushSize);setBrushColor(savedBrushColor);
 manifest=await readJson('models/manifest.json');for(const item of manifest.models){const option=document.createElement('option');option.value=item.id;option.textContent=item.label;$('model').append(option);}model=manifest.models[0];
 $('model').onchange=()=>switchModel($('model').value);$('model-male').onclick=()=>switchModel('Male');$('model-female').onclick=()=>switchModel('Female');$('area').onchange=()=>{if(busy)return;region=$('area').value;$('region-title').textContent=region;isolation=null;renderRegions();refresh({fit:true});};await loadModel();
 }catch(error){status(`Viewer could not start. ${error.message}`,true);}}
renderBodyMap();renderAcupuncture();start();
