import {NativeViewerEngine} from './native-viewer-engine.js';
import {ACUPUNCTURE_CHANNELS} from './acupuncture-layer.js';
import './style.css';
import './dock.css';
import './acu-map.css';

const $=id=>document.getElementById(id);
let engine,manifest,model,busy=false,toastTimer,prescriptionLibrary=[],activePrescription=null,availablePointIds=new Set();
let showPoints=true,showLines=true,showZones=true,dashedLines=true,sectionMode='full',channels=new Set(ACUPUNCTURE_CHANNELS.map(([id])=>id));
let showRulers=true,rulerRules=null,selectedPointId=null,selectedRulerNames=new Set();
let editState={editing:false,dirty:false,selectedKey:null,canUndo:false,model:'Male',adjusted:0};
let pointMenuChannel='BL',lastSelection=null;
const CALIBRATION_KEY='acu-map-native-calibration-v1';
const PRESCRIPTIONS_KEY='acu-map-prescriptions-v1';

function status(message,error=false){$('loading').hidden=false;$('load-text').textContent=message;$('retry').hidden=!error;$('progress').hidden=error;}
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,2600);}
function setBusy(value){busy=value;document.querySelectorAll('button,select,input,textarea').forEach(control=>{if(control.id!=='retry')control.disabled=value;});if(!value){renderEditState(editState);$('add-selected-point').disabled=!selectedPointId;$('clear-prescription').disabled=!activePrescription;}}
function closeMenus(){document.querySelectorAll('.floating-tools details').forEach(menu=>menu.open=false);}
function setPointPanel(open){const panel=$('point-panel'),toggle=$('point-panel-toggle');panel.classList.toggle('is-open',open);panel.setAttribute('aria-hidden',String(!open));toggle.setAttribute('aria-expanded',String(open));if(open){closeMenus();setDrawer(false);setPrescriptionDrawer(false);requestAnimationFrame(()=>$('search').focus());}}
function setDrawer(open){$('selection-drawer').classList.toggle('is-open',open);$('selection-drawer').setAttribute('aria-hidden',String(!open));$('selection-toggle').setAttribute('aria-expanded',String(open));if(open){setPointPanel(false);setPrescriptionDrawer(false);}requestAnimationFrame(()=>engine?.updateViewport());}
function selection(record){if(!record?.acupoint)return;lastSelection=record;selectRulers(record.pointId);$('add-selected-point').disabled=false;$('point-summary-label').textContent=record.compactLabel;$('selection-toggle').hidden=false;$('selection-toggle').setAttribute('aria-label',`Open details for ${record.compactLabel}. ${record.selection==='paired'?'Both sides selected':`${record.side} location selected`}.`);$('selected-name').textContent=record.compactLabel;$('selected-meta').textContent=`${record.region} · Source review pending`;$('selected-info').replaceChildren();for(const section of record.sections||[]){const heading=document.createElement('h3'),text=document.createElement('p');heading.textContent=section.name;text.textContent=section.text||'';$('selected-info').append(heading,text);}const note=document.createElement('p');note.className='source-note';note.textContent='The body mesh, point coordinates, and point-specific ruler rules were extracted from the supplied 免费找穴位神器 APK. Anatomical placement and clinical content remain pending practitioner review.';$('selected-info').append(note);}

function prescriptions(){try{const value=JSON.parse(localStorage.getItem(PRESCRIPTIONS_KEY)||'[]');return Array.isArray(value)?value:[];}catch{return [];}}
function writePrescriptions(items){localStorage.setItem(PRESCRIPTIONS_KEY,JSON.stringify(items));}
function prescriptionId(){return globalThis.crypto?.randomUUID?.()||`prescription-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function normalizePoint(value){return value.trim().toUpperCase().replace(/^(KD)(\d+)$/,'KI$2').replace(/^(SJ|TW)(\d+)$/,'TE$2').replace(/[-_]/g,'');}
function parsePoints(value){const points=[...new Set(value.split(/[\s,;，、]+/).map(normalizePoint).filter(Boolean))];return {points:points.filter(point=>availablePointIds.has(point)),invalid:points.filter(point=>!availablePointIds.has(point))};}
function setPrescriptionDrawer(open){const drawer=$('prescription-drawer');drawer.classList.toggle('is-open',open);drawer.setAttribute('aria-hidden',String(!open));$('prescription-toggle').setAttribute('aria-expanded',String(open));if(open){setDrawer(false);setPointPanel(false);renderPrescriptions();requestAnimationFrame(()=>$('prescription-search').focus());}requestAnimationFrame(()=>engine?.updateViewport());}
function clearPrescriptionHighlight(){activePrescription=null;engine?.setPrescriptionHighlights([]);$('clear-prescription').disabled=true;document.querySelectorAll('.prescription-card[aria-pressed="true"]').forEach(card=>card.setAttribute('aria-pressed','false'));}
function activatePrescription(record){activePrescription=record;showPoints=true;engine?.setPrescriptionHighlights(record.points);$('clear-prescription').disabled=false;renderChannels();document.querySelectorAll('.prescription-card').forEach(card=>card.setAttribute('aria-pressed',String(card.dataset.prescriptionId===record.id)));toast(`${record.points.length} point${record.points.length===1?'':'s'} highlighted`);}
function statusLabel(status){return status==='approved'?'Approved':status==='sources_reviewed'?'Sources reviewed':status==='awaiting_approval'?'Awaiting approval':'Pending review';}
function prescriptionCard(record,custom=false){const card=document.createElement('article');card.className='prescription-card';card.dataset.prescriptionId=record.id;card.setAttribute('aria-pressed',String(activePrescription?.id===record.id));const select=document.createElement('button');select.type='button';select.className='prescription-select';const heading=document.createElement('strong'),description=document.createElement('span'),points=document.createElement('span');heading.textContent=record.title;description.textContent=record.description||'No description';points.className='prescription-points';points.textContent=record.points.join(' · ');select.append(heading,description,points);select.onclick=()=>activatePrescription(record);card.append(select);const footer=document.createElement('footer'),badge=document.createElement('small');badge.textContent=custom?'User-authored':statusLabel(record.status);footer.append(badge);if(custom){const edit=document.createElement('button'),remove=document.createElement('button');edit.type=remove.type='button';edit.textContent='Edit';remove.textContent='Delete';edit.onclick=()=>openPrescriptionEditor(record);remove.onclick=()=>{if(!confirm(`Delete “${record.title}”?`))return;const next=prescriptions().filter(item=>item.id!==record.id);writePrescriptions(next);if(activePrescription?.id===record.id)clearPrescriptionHighlight();renderPrescriptions();toast('Prescription deleted');};footer.append(edit,remove);}else{const copy=document.createElement('button');copy.type='button';copy.textContent='Save copy';copy.onclick=()=>openPrescriptionEditor({...record,id:'',title:record.title.replace(/^[^—]+—\s*/,''),description:record.description});footer.append(copy);}card.append(footer);return card;}
function renderPrescriptions(){const query=$('prescription-search').value.trim().toLowerCase(),saved=prescriptions(),match=record=>!query||[record.title,record.description,record.condition,record.pattern,record.system,...record.points].filter(Boolean).join(' ').toLowerCase().includes(query),savedRows=saved.filter(match),libraryRows=prescriptionLibrary.filter(match);$('prescription-count').textContent=String(saved.length);$('saved-prescription-count').textContent=String(savedRows.length);$('library-prescription-count').textContent=libraryRows.length>80?`${libraryRows.length} · first 80`:String(libraryRows.length);$('saved-prescriptions').replaceChildren(...savedRows.map(record=>prescriptionCard(record,true)));$('library-prescriptions').replaceChildren(...libraryRows.slice(0,80).map(record=>prescriptionCard(record,false)));if(!savedRows.length){const empty=document.createElement('p');empty.className='prescription-empty';empty.textContent=query?'No saved prescription matches this search.':'Create a prescription to keep a reusable point combination with your own description.';$('saved-prescriptions').append(empty);}if(!libraryRows.length){const empty=document.createElement('p');empty.className='prescription-empty';empty.textContent='No built-in combination matches this search.';$('library-prescriptions').append(empty);}}
function openPrescriptionEditor(record=null){$('prescription-editor').hidden=false;$('prescription-id').value=record?.id||'';$('prescription-name').value=record?.title||'';$('prescription-description').value=record?.description||'';$('prescription-points').value=(record?.points||[]).join(', ');$('prescription-editor-title').textContent=record?.id?'Edit prescription':'New prescription';$('prescription-editor-status').textContent='';setPrescriptionDrawer(true);$('prescription-name').focus();}
function closePrescriptionEditor(){$('prescription-editor').hidden=true;$('prescription-editor-status').textContent='';}
function previewPrescription(){const result=parsePoints($('prescription-points').value);if(result.invalid.length){$('prescription-editor-status').textContent=`Not found on this model: ${result.invalid.join(', ')}`;return false;}if(!result.points.length){$('prescription-editor-status').textContent='Add at least one valid point code.';return false;}engine?.setPrescriptionHighlights(result.points);$('clear-prescription').disabled=false;$('prescription-editor-status').textContent=`Previewing ${result.points.length} point${result.points.length===1?'':'s'} on the model.`;return result.points;}
function savePrescription(){const title=$('prescription-name').value.trim(),result=parsePoints($('prescription-points').value);if(!title){$('prescription-editor-status').textContent='Enter a prescription name.';$('prescription-name').focus();return;}if(result.invalid.length){$('prescription-editor-status').textContent=`Remove or correct: ${result.invalid.join(', ')}`;return;}if(!result.points.length){$('prescription-editor-status').textContent='Add at least one valid point code.';return;}const items=prescriptions(),id=$('prescription-id').value||prescriptionId(),record={id,title,description:$('prescription-description').value.trim(),points:result.points,updatedAt:new Date().toISOString()},index=items.findIndex(item=>item.id===id);if(index>=0)items[index]=record;else items.unshift(record);try{writePrescriptions(items);closePrescriptionEditor();$('prescription-search').value='';renderPrescriptions();activatePrescription(record);toast(index>=0?'Prescription updated':'Prescription saved on this device');}catch(error){$('prescription-editor-status').textContent=`Could not save: ${error.message}`;}}
function renderChannels(){const target=$('acupuncture-channels');target.replaceChildren();for(const [id,name,color] of ACUPUNCTURE_CHANNELS){const button=document.createElement('button');button.type='button';button.dataset.channel=id;button.style.setProperty('--channel-color',color);button.setAttribute('aria-pressed',String(channels.has(id)));button.innerHTML='<i aria-hidden="true"></i><span></span>';button.querySelector('span').textContent=`${id} · ${name}`;button.onclick=()=>{channels.has(id)?channels.delete(id):channels.add(id);applyAcupuncture();};target.append(button);}$('acupuncture-points').setAttribute('aria-pressed',String(showPoints));$('acupuncture-lines').setAttribute('aria-pressed',String(showLines));$('acupuncture-zones').setAttribute('aria-pressed',String(showZones));const layers=[];if(showPoints)layers.push('P');if(showLines)layers.push('L');if(showZones)layers.push('皮');$('acupuncture-count').textContent=layers.join(' · ')||'Off';}
function applyAcupuncture(){renderChannels();engine?.setAcupuncture({points:showPoints,lines:showLines,zones:showZones,dashed:dashedLines,channels});list();}
function applySection(mode){sectionMode=mode;engine?.setSection(mode);for(const id of ['full','left','right'])$(`section-${id}`).setAttribute('aria-pressed',String(id===mode));$('section-count').textContent=mode==='full'?'Full':mode==='left'?'Hide L':'Hide R';}
function renderRulers(){const count=selectedRulerNames.size;$('ruler-master').setAttribute('aria-pressed',String(showRulers));$('ruler-master').setAttribute('aria-label',showRulers?'Disable automatic point rulers':'Enable automatic point rulers');$('ruler-master').textContent=showRulers?'Auto on':'Auto off';$('ruler-count').textContent=!showRulers?'Off':selectedPointId?(count?`${selectedPointId} · ${count}`:`${selectedPointId} · none`):'Select point';$('ruler-selection').textContent=!selectedPointId?'Select an acupoint to show its original APK ruler reference.':count?`${selectedPointId} uses ${count} ${count===1?'reference mark':'reference marks'}. Selecting another point replaces these.`:`${selectedPointId} has no ruler reference in the original APK.`;}
async function applyRulers(){renderRulers();if(!engine)return;const visible=showRulers&&selectedRulerNames.size>0;if(visible&&!engine.rulers)$('ruler-count').textContent='Loading…';try{await engine.setRulers({visible,names:selectedRulerNames});renderRulers();}catch(error){showRulers=false;renderRulers();toast(`Could not load rulers: ${error.message}`);}}
function selectRulers(pointId){selectedPointId=pointId||null;selectedRulerNames=new Set(selectedPointId&&rulerRules?.points?.[selectedPointId]||[]);applyRulers();}
function renderPointMeridians(){const target=$('point-meridians');target.replaceChildren();for(const [id,name,color] of ACUPUNCTURE_CHANNELS){const button=document.createElement('button');button.type='button';button.dataset.channel=id;button.style.setProperty('--channel-color',color);button.setAttribute('aria-pressed',String(id===pointMenuChannel));button.innerHTML='<i aria-hidden="true"></i><span></span>';button.querySelector('span').textContent=name;button.onclick=()=>{pointMenuChannel=id;$('search').value='';renderPointMeridians();list();};target.append(button);}}
function list(){const query=$('search').value.trim(),all=engine?.searchAcupuncture(query,400)||[],rows=query?all:all.filter(row=>row.channel===pointMenuChannel),channel=ACUPUNCTURE_CHANNELS.find(([id])=>id===pointMenuChannel);$('point-panel-title').textContent=query?'Search results':`${channel?.[1]||pointMenuChannel} meridian`;$('count').textContent=`${rows.length} point${rows.length===1?'':'s'}`;$('structures').replaceChildren();for(const row of rows){const button=document.createElement('button');button.className='point-tile';button.type='button';button.setAttribute('role','listitem');button.setAttribute('aria-label',row.compactLabel);button.innerHTML='<span class="point-chinese"></span><strong></strong>';button.querySelector('.point-chinese').textContent=row.names?.chinese||'—';button.querySelector('strong').textContent=row.id;button.onclick=()=>{showPoints=true;channels.add(row.channel);applyAcupuncture();engine.focusAcupuncturePair(row.id);setPointPanel(false);};$('structures').append(button);}if(!rows.length){const empty=document.createElement('p');empty.className='point-empty';empty.textContent='No matching point. Try LI4, Hegu, 合谷, or a meridian name.';$('structures').append(empty);}}
function renderEditState(state){editState=state;const edit=$('acupuncture-edit');edit.setAttribute('aria-pressed',String(state.editing));edit.textContent=state.editing?'Finish editing':'Edit points';$('acupuncture-save').disabled=busy||!state.dirty;$('acupuncture-undo').disabled=busy||!state.canUndo;$('acupuncture-reset-point').disabled=busy||!state.selectedKey;$('acupuncture-reset-model').disabled=busy||!state.adjusted;$('acupuncture-edit-status').textContent=state.editing?`${state.adjusted} adjusted${state.selectedKey?` · ${state.selectedKey}`:''}${state.dirty?' · unsaved':''}. Drag points on the body.`:`${state.adjusted} adjusted for ${state.model}${state.dirty?' · unsaved':''}.`;}
function saveCalibration(){try{localStorage.setItem(CALIBRATION_KEY,JSON.stringify(engine.exportAcupunctureCalibration()));engine.markAcupunctureSaved();toast('Point adjustments saved on this device');}catch(error){toast(`Could not save: ${error.message}`);}}
function downloadCalibration(){const blob=new Blob([JSON.stringify(engine.exportAcupunctureCalibration(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`acu-map-native-calibration-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function loadModel(){if(busy)return;setBusy(true);status(`Loading original ${model.label.toLowerCase()} model…`);try{await engine.prepare(model);applySection(sectionMode);applyAcupuncture();await applyRulers();engine.fit([0,0,1]);$('loading').hidden=true;$('model').value=model.id;$('model-male').setAttribute('aria-pressed',String(model.id==='Male'));$('model-female').setAttribute('aria-pressed',String(model.id==='Female'));}catch(error){status(`Could not load the source model. ${error.message}`,true);}finally{setBusy(false);}}
async function switchModel(id){const next=manifest.models.find(item=>item.id===id);if(!next||next===model)return;model=next;selectedPointId=null;selectedRulerNames.clear();lastSelection=null;$('selection-toggle').hidden=true;$('add-selected-point').disabled=true;setDrawer(false);await loadModel();}

$('search').oninput=list;$('point-panel-toggle').onclick=()=>setPointPanel(!$('point-panel').classList.contains('is-open'));$('close-point-panel').onclick=()=>setPointPanel(false);$('fit').onclick=()=>engine.fit();$('front').onclick=()=>engine.fit([0,0,1]);$('back').onclick=()=>engine.fit([0,0,-1]);$('selection-toggle').onclick=()=>lastSelection&&setDrawer(!$('selection-drawer').classList.contains('is-open'));$('close-selection').onclick=()=>setDrawer(false);
$('prescription-toggle').onclick=()=>setPrescriptionDrawer(!$('prescription-drawer').classList.contains('is-open'));$('close-prescriptions').onclick=()=>setPrescriptionDrawer(false);$('new-prescription').onclick=()=>openPrescriptionEditor();$('cancel-prescription').onclick=closePrescriptionEditor;$('clear-prescription').onclick=clearPrescriptionHighlight;$('prescription-search').oninput=renderPrescriptions;$('preview-prescription').onclick=previewPrescription;$('save-prescription').onclick=savePrescription;$('add-selected-point').onclick=()=>{if(!selectedPointId)return;const result=parsePoints($('prescription-points').value),points=[...result.points];if(!points.includes(selectedPointId))points.push(selectedPointId);$('prescription-points').value=points.join(', ');previewPrescription();};
$('acupuncture-points').onclick=()=>{showPoints=!showPoints;applyAcupuncture();};$('acupuncture-lines').onclick=()=>{showLines=!showLines;applyAcupuncture();};$('acupuncture-zones').onclick=()=>{showZones=!showZones;applyAcupuncture();};$('acupuncture-all').onclick=()=>{channels=new Set(ACUPUNCTURE_CHANNELS.map(([id])=>id));applyAcupuncture();};$('acupuncture-clear').onclick=()=>{channels.clear();applyAcupuncture();};
$('section-full').onclick=()=>applySection('full');$('section-left').onclick=()=>applySection('left');$('section-right').onclick=()=>applySection('right');$('line-style').onclick=()=>{dashedLines=!dashedLines;$('line-style').setAttribute('aria-pressed',String(dashedLines));$('line-style').querySelector('span').textContent=dashedLines?'Perforated meridian lines':'Solid meridian lines';applyAcupuncture();};
$('ruler-master').onclick=()=>{showRulers=!showRulers;applyRulers();};
$('acupuncture-edit').onclick=()=>{engine.setAcupunctureEditing(!editState.editing);showPoints=true;applyAcupuncture();closeMenus();};$('acupuncture-save').onclick=saveCalibration;$('acupuncture-undo').onclick=()=>engine.undoAcupuncture();$('acupuncture-reset-point').onclick=()=>engine.resetSelectedAcupuncture()||toast('This point has no saved adjustment');$('acupuncture-reset-model').onclick=()=>{if(confirm(`Reset every adjusted point on the ${model.label.toLowerCase()} model?`))engine.resetAcupunctureModel();};$('acupuncture-export').onclick=downloadCalibration;$('acupuncture-import').onclick=()=>$('acupuncture-import-file').click();$('acupuncture-import-file').onchange=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{engine.setAcupunctureCalibration(JSON.parse(await file.text()));saveCalibration();toast(`Imported ${file.name}`);}catch(error){toast(`Import failed: ${error.message}`);}};
$('model').onchange=()=>switchModel($('model').value);$('model-male').onclick=()=>switchModel('Male');$('model-female').onclick=()=>switchModel('Female');$('retry').onclick=()=>loadModel();

async function start(){try{engine=new NativeViewerEngine($('canvas'),selection,()=>status('Graphics memory was exhausted. Reload to continue.',true),renderEditState);const [,rulerResponse,prescriptionResponse]=await Promise.all([engine.loadAcupuncture('acupuncture-data.json','acupuncture-native-paths.json'),fetch('acupuncture-rulers.json'),fetch('prescription-library.json')]);if(!rulerResponse.ok)throw Error(`Ruler rules returned ${rulerResponse.status}`);if(!prescriptionResponse.ok)throw Error(`Prescription library returned ${prescriptionResponse.status}`);rulerRules=await rulerResponse.json();prescriptionLibrary=(await prescriptionResponse.json()).records||[];availablePointIds=new Set(engine.searchAcupuncture('',10000).map(point=>point.id));try{const saved=JSON.parse(localStorage.getItem(CALIBRATION_KEY)||'null');if(saved)engine.setAcupunctureCalibration(saved);}catch{}renderChannels();renderRulers();renderPrescriptions();renderPointMeridians();list();manifest=await (await fetch('models/manifest.json')).json();for(const item of manifest.models){const option=document.createElement('option');option.value=item.id;option.textContent=item.label;$('model').append(option);}model=manifest.models[0];await loadModel();}catch(error){status(`Viewer could not start. ${error.message}`,true);}}
for(const detail of document.querySelectorAll('.floating-tools details'))detail.addEventListener('toggle',()=>{if(detail.open)for(const other of document.querySelectorAll('.floating-tools details'))if(other!==detail)other.open=false;});
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if($('selection-drawer').classList.contains('is-open'))setDrawer(false);else if($('point-panel').classList.contains('is-open'))setPointPanel(false);else if($('prescription-drawer').classList.contains('is-open'))setPrescriptionDrawer(false);});
start();
